// import { authOptions } from "../../pages/api/auth/[...nextauth]";
// import { getServerSession } from "next-auth";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import SessionProvider from "./SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await getServerSession(authOptions);
  return (
    <html lang="ja">
      <body className={inter.className}>
      <div className="flex flex-col space-y-10 justify-center items-center mb-5 mt-12">
      {/* <SessionProvider session={session} > */}
      {children}
      {/* </SessionProvider> */}
      </div>
      </body>
    </html>
  );
}
